import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-5 bg-slate-200 h-screen `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
