import Header from "@/components/organisms/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={`w-full max-w-screen-xl flex flex-col m-auto`}
        suppressHydrationWarning={true}
      >
        {/* <main className="grow">{children}</main> */}
        {children}
      </body>
    </html>
  );
}
